#include "arduino_secrets.h"
/*
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/3a38bdea-92bb-41e7-93d4-f1d91d24a5ce

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  bool power;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#include <Servo.h>

Servo servo1;

void setup() {
  Serial.begin(9600);
  delay(1500);
  servo1.attach(10);
  initProperties();
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);

  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();


  //pinMode(LED_BUILTIN, OUTPUT);
}

void loop() {
  ArduinoCloud.update();

  if (!power) {
    turnOff();
  }

  // Your code here
}

void onPowerChange() {

  // Add your code here to act upon Power change
}

void turnOff() {
  int angle = 90;
  servo1.write(0);
  angle = 120;
  servo1.write(angle);
  delay(2000);
  servo1.write(1);
  delay(2000);
}

